language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - python-dev
      - python-numpy

before_script:
  - git clone -b 3.4 https://github.com/opencv/opencv
  - git clone -b face_fix_landmarks_python https://github.com/berak/opencv_contrib

script:
  - python --version
  - pwd
  - mkdir ocv
  - cd opencv
  - mkdir build
  - cd build
  - echo -n cmake -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -DBUILD_LIST=core,calib3d,imgproc,xfeatures2d,features2d,imgcodecs,objdetect,video,photo,flann,face,python2,opencv_python_bindings_generator,java -WITH_ITT= >> cm.sh
  - echo -n OFF -WITH_IPP=OFF -DBUILD_IPP_IW=OFF -DBUILD_WITH_DYNAMIC_IPP=OFF -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS= >> cm.sh
  - echo -n OFF -DBUILD_PERF_TESTS=OFF -DBUILD_DOCS=OFF -DBUILD_examples=OFF -DWITH_OPENEXR=OFF -DBUILD_OPENEXR= >> cm.sh
  - echo -n OFF -Wall" -DCV_TRACE=OFF -DWITH_TIFF=OFF -DWITH_EXR=OFF -DCMAKE_INSTALL_PREFIX= >> cm.sh
  - echo -n ../../ocv -DBUILD_ZLIB=ON -DWITH_WEBP=OFF -DWITH_JASPER=>> cm.sh
  - echo -n OFF >> cm.sh
  - echo -G \"Unix Makefiles\" .. >> cm.sh
  - cat cm.sh
  - bash cm.sh
  - make -j8 install
  - #ls modules/java_bindings_generator/gen
  - #cat modules/python_bindings_generator/pyopencv_generated_types.h
  - #cat modules/java/jar/opencv/java/org/opencv/bgsegm/BackgroundSubtractorCNT.java
  - #cat modules/java/gen/face+MACE.java
  - #python ../modules/ts/misc/run.py . -a -t java
  - cd ..
  - cd ..
  - cp opencv/.cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat face_landmark_model.dat
  - curl  https://raw.githubusercontent.com/kurnianggoro/GSOC2017/master/data/lbfmodel.yaml > lbfmodel.yaml
  - ls -l
  - echo running ant
  - ant -DocvJarDir=ocv/share/OpenCV/java -DocvLibDir=ocv/share/OpenCV/java
  - #export PATH=${PATH}:/home/travis/build/berak/tt/ocv/lib/python2.7/dist-packages
  - python landmarks.py

notifications:
  email: false
